import {
  FaLayerGroup,
  FaCloud,
  FaLaptopCode,
  FaIndustry,
  FaHospital,
  FaShoppingCart,
  FaGlobe,
  FaUserShield,
} from "react-icons/fa";

// Industry categories
export const industries = [
  { id: "all", name: "All Industries" },
  { id: "finance", name: "Financial Services" },
  { id: "healthcare", name: "Healthcare" },
  { id: "retail", name: "Retail & E-commerce" },
  { id: "manufacturing", name: "Manufacturing" },
  { id: "logistics", name: "Logistics & Transportation" },
  { id: "technology", name: "Technology" },
];

export const services = [
  { id: "all", name: "All Services" },
  { id: "development", name: "Software Development" },
  { id: "cloud", name: "Cloud & AI" },
  { id: "automation", name: "Automation" },
  { id: "mobile", name: "Mobile Apps" },
  { id: "security", name: "Cybersecurity" },
  { id: "analytics", name: "Data Analytics" },
];

// Case studies data
export const caseStudies = [
  {
    id: 1,
    title: "AI-Powered Inventory Management System",
    industry: "retail",
    services: ["development", "cloud", "automation"],
    clientName: "GlobalMart Retail Chain",
    clientDescription:
      "A multinational retail corporation with over 500 stores across 12 countries",
    challengeTitle: "Inventory Challenges at Scale",
    challengeDescription:
      "GlobalMart was struggling with significant inventory discrepancies across their stores, leading to stockouts, overstocking, and millions in lost revenue. Their legacy inventory system couldn't handle the scale of their operations, resulting in manual workarounds and critical data delays.",
    icon: <FaLayerGroup className="text-purple-500" />,
    bgColor: "from-purple-500/20 to-pink-500/20",
    accentColor: "purple",
    image: "/images/case-studies/retail.jpg",
    logo: "/images/clients/globalmart-logo.svg",
    stats: [
      { label: "Stockout Reduction", value: "78%" },
      { label: "Inventory Turn Increase", value: "24%" },
      { label: "Annual Savings", value: "$4.2M" },
      { label: "Implementation Time", value: "5 months" },
    ],
    solution: [
      "Developed a custom AI-powered inventory management system that integrates with existing POS and ERP systems",
      "Implemented predictive stock management using machine learning algorithms trained on historical sales data",
      "Created a real-time inventory tracking system with automated alerts and reordering capabilities",
      "Designed an intuitive dashboard for store managers with actionable insights and recommendations",
    ],
    technologies: [
      "React",
      "Node.js",
      "TensorFlow",
      "AWS",
      "MongoDB",
      "Python",
    ],
    testimonial: {
      quote:
        "The inventory management system CodeKet built has completely transformed our operations. We've seen dramatic improvements in stock accuracy and significant cost savings.",
      author: "Sarah Johnson",
      title: "CTO, GlobalMart",
    },
    results: [
      "Reduced stockouts by 78% within the first three months of deployment",
      "Increased inventory turn by 24%, freeing up $12M in working capital",
      "Cut manual inventory tasks by 92%, allowing staff to focus on customer service",
      "Improved forecast accuracy from 65% to 94% with predictive AI algorithms",
      "Achieved full ROI within 11 months of implementation",
    ],
  },
  {
    id: 2,
    title: "Secure Banking Platform Modernization",
    industry: "finance",
    services: ["development", "security", "cloud"],
    clientName: "International Banking Corporation",
    clientDescription:
      "A global financial institution serving over 25 million customers with operations in 40+ countries",
    challengeTitle: "Legacy System Limitations",
    challengeDescription:
      "IBC was operating on an outdated banking platform built 15+ years ago. The system was increasingly costly to maintain, lacked modern security features, and couldn't support the bank's digital transformation initiatives. Customer experience was suffering with slow transaction times and limited self-service capabilities.",
    icon: <FaLaptopCode className="text-teal-500" />,
    bgColor: "from-teal-500/20 to-cyan-500/20",
    accentColor: "teal",
    image: "/images/case-studies/banking.jpg",
    logo: "/images/clients/ibc-logo.svg",
    stats: [
      { label: "Uptime", value: "99.999%" },
      { label: "Transaction Cost Reduction", value: "42%" },
      { label: "Active Digital Users", value: "3.2M" },
      { label: "Security Incidents", value: "Zero" },
    ],
    solution: [
      "Architected a microservices-based banking platform with cloud-native technologies",
      "Implemented advanced security measures including biometric authentication and real-time fraud detection",
      "Developed a comprehensive API layer to enable fintech partnerships and service integrations",
      "Created responsive web and mobile interfaces with enhanced self-service capabilities",
    ],
    technologies: [
      "Angular",
      "Java Spring",
      "Kubernetes",
      "MongoDB",
      "AWS",
      "OAuth 2.0",
      "Kafka",
    ],
    testimonial: {
      quote:
        "CodeKet delivered a banking platform that not only addressed our security and performance needs but has become the foundation of our digital transformation. Their expertise in financial systems was evident throughout the project.",
      author: "Michael Chen",
      title: "CIO, International Banking Corporation",
    },
    results: [
      "Achieved 99.999% platform uptime since launch",
      "Reduced transaction processing costs by 42%",
      "Increased digital customer engagement by 87%",
      "Enabled rapid deployment of new features (from months to days)",
      "Maintained PCI-DSS Level 1 compliance with zero security incidents",
      "Onboarded 15 fintech partners within first year using new API ecosystem",
    ],
  },
  {
    id: 3,
    title: "Patient Data Platform & AI Diagnostics",
    industry: "healthcare",
    services: ["development", "cloud", "analytics"],
    clientName: "National Healthcare Network",
    clientDescription:
      "A leading healthcare provider with 12 hospitals and 30+ clinics serving over 2 million patients annually",
    challengeTitle: "Fragmented Patient Data",
    challengeDescription:
      "NHN was struggling with siloed patient data across different facilities and departments. This fragmentation led to delayed diagnoses, duplicate testing, and inefficient care coordination. Doctors lacked a unified view of patient history, and manually reviewing medical images was causing diagnostic bottlenecks.",
    icon: <FaHospital className="text-green-500" />,
    bgColor: "from-green-500/20 to-teal-500/20",
    accentColor: "green",
    image: "/images/case-studies/healthcare.jpg",
    logo: "/images/clients/nhn-logo.svg",
    stats: [
      { label: "Faster Diagnostics", value: "68%" },
      { label: "Improved Outcomes", value: "24%" },
      { label: "Patient Records", value: "1.2M+" },
      { label: "System Integrations", value: "15" },
    ],
    solution: [
      "Built a HIPAA-compliant unified patient data platform that integrates data from all facilities and departments",
      "Developed AI-assisted diagnostic tools for radiology and pathology using deep learning models",
      "Created a secure physician portal with comprehensive patient views and clinical decision support",
      "Implemented predictive analytics for patient risk stratification and preventive care recommendations",
    ],
    technologies: [
      "React",
      "Python",
      "TensorFlow",
      "Google Cloud",
      "FHIR API",
      "PostgreSQL",
      "Docker",
    ],
    testimonial: {
      quote:
        "The platform CodeKet developed has revolutionized how we deliver care. Our physicians now have instant access to complete patient histories, and the AI diagnostic tools have significantly improved both accuracy and efficiency.",
      author: "Dr. Lisa Rodriguez",
      title: "Chief Medical Officer, National Healthcare Network",
    },
    results: [
      "Accelerated diagnostic times by 68% through AI-assisted image analysis",
      "Improved treatment outcomes by 24% with comprehensive patient data access",
      "Reduced duplicate testing by 92%, saving an estimated $3.6M annually",
      "Decreased average hospital stay by 1.7 days through better care coordination",
      "Seamlessly integrated with 15 existing clinical and administrative systems",
      "Maintained 100% HIPAA compliance with zero data breaches",
    ],
  },
  {
    id: 4,
    title: "Smart Factory Automation System",
    industry: "manufacturing",
    services: ["automation", "cloud", "analytics"],
    clientName: "Advanced Manufacturing Group",
    clientDescription:
      "A global industrial manufacturer with 12 production facilities specializing in precision components",
    challengeTitle: "Production Inefficiencies and Quality Issues",
    challengeDescription:
      "AMG was experiencing high maintenance costs, production delays, and inconsistent product quality across their manufacturing facilities. Their existing systems couldn't provide real-time visibility into operations, and equipment failures were causing costly downtime. Manual quality inspection processes were time-consuming and error-prone.",
    icon: <FaIndustry className="text-amber-500" />,
    bgColor: "from-amber-500/20 to-orange-500/20",
    accentColor: "amber",
    image: "/images/case-studies/manufacturing.jpg",
    logo: "/images/clients/amg-logo.svg",
    stats: [
      { label: "Downtime Reduction", value: "63%" },
      { label: "Quality Improvement", value: "42%" },
      { label: "Production Increase", value: "28%" },
      { label: "Maintenance Cost Saving", value: "$2.8M" },
    ],
    solution: [
      "Implemented an IoT-based factory monitoring system with thousands of sensors across production lines",
      "Developed predictive maintenance algorithms to identify potential equipment failures before they occur",
      "Created an AI-powered quality inspection system using computer vision and deep learning",
      "Built a real-time analytics dashboard for production managers with actionable insights",
    ],
    technologies: [
      "Industrial IoT",
      "Microsoft Azure",
      "Python",
      "TensorFlow",
      "Power BI",
      "C#",
      "MQTT",
    ],
    testimonial: {
      quote:
        "The smart factory system that CodeKet designed has transformed our manufacturing operations. We've seen dramatic improvements in uptime, quality, and overall equipment effectiveness across all our facilities.",
      author: "James Wilson",
      title: "VP of Operations, Advanced Manufacturing Group",
    },
    results: [
      "Reduced unplanned downtime by 63% through predictive maintenance",
      "Improved product quality rates from 92% to 99.2% with AI-based inspection",
      "Increased overall production capacity by 28% without additional equipment",
      "Decreased maintenance costs by 42%, saving $2.8M annually",
      "Cut energy consumption by 18% through optimized equipment scheduling",
      "Reduced time-to-market for new products by 35% with improved production insights",
    ],
  },
  {
    id: 5,
    title: "Global Logistics Optimization Platform",
    industry: "logistics",
    services: ["development", "analytics", "automation"],
    clientName: "WorldWide Logistics Corporation",
    clientDescription:
      "A major international logistics provider handling over 5 million shipments annually across 60+ countries",
    challengeTitle: "Supply Chain Complexity and Visibility Gaps",
    challengeDescription:
      "WWLC was struggling with supply chain visibility, routing inefficiencies, and manual coordination processes across their global operations. Customers lacked real-time tracking capabilities, and route planning relied heavily on dispatcher experience rather than data-driven decision making.",
    icon: <FaGlobe className="text-blue-500" />,
    bgColor: "from-blue-500/20 to-indigo-500/20",
    accentColor: "blue",
    image: "/images/case-studies/logistics.jpg",
    logo: "/images/clients/wwlc-logo.svg",
    stats: [
      { label: "Operational Efficiency", value: "+42%" },
      { label: "Fuel Savings", value: "18%" },
      { label: "On-time Delivery", value: "97.5%" },
      { label: "Annual Savings", value: "$1.2M" },
    ],
    solution: [
      "Developed an end-to-end logistics management platform with real-time shipment tracking",
      "Implemented AI-driven route optimization algorithms considering multiple variables (traffic, weather, vehicle capacity)",
      "Created a driver mobile app with turn-by-turn navigation and electronic documentation",
      "Built a customer portal with real-time visibility and self-service capabilities",
    ],
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Google Maps API",
      "TensorFlow",
      "Redis",
      "AWS",
    ],
    testimonial: {
      quote:
        "CodeKet delivered a logistics platform that has completely transformed our operations. The real-time visibility and AI-powered routing have dramatically improved our efficiency and customer satisfaction.",
      author: "Robert Martinez",
      title: "CEO, WorldWide Logistics Corporation",
    },
    results: [
      "Increased operational efficiency by 42% through optimized routing and reduced manual processes",
      "Improved on-time delivery rates from 82% to 97.5%",
      "Reduced fuel consumption by 18% with AI-optimized routes",
      "Decreased administrative workload by 65% through automation",
      "Cut customer service calls by 72% with self-service tracking portal",
      "Achieved annual savings of $1.2M in operational costs",
    ],
  },
  {
    id: 6,
    title: "Secure Cloud Migration & DevOps Transformation",
    industry: "technology",
    services: ["cloud", "security", "automation"],
    clientName: "TechSolutions SaaS Platform",
    clientDescription:
      "A growing SaaS company providing enterprise workflow solutions to 500+ corporate clients",
    challengeTitle: "Scaling Challenges and Security Concerns",
    challengeDescription:
      "TechSolutions was experiencing performance issues during peak usage, deployment delays with their monolithic architecture, and increasing security concerns from enterprise clients. Their on-premises infrastructure was becoming a constraint to growth, and manual deployment processes were causing frequent release delays.",
    icon: <FaCloud className="text-cyan-500" />,
    bgColor: "from-cyan-500/20 to-blue-500/20",
    accentColor: "cyan",
    image: "/images/case-studies/cloud.jpg",
    logo: "/images/clients/techsolutions-logo.svg",
    stats: [
      { label: "Release Frequency", value: "10x" },
      { label: "Infrastructure Cost", value: "-35%" },
      { label: "Uptime", value: "99.99%" },
      { label: "Security Vulnerabilities", value: "-92%" },
    ],
    solution: [
      "Designed and implemented a secure cloud migration strategy to AWS",
      "Refactored monolithic application into microservices architecture",
      "Built comprehensive CI/CD pipelines with automated testing and security scanning",
      "Implemented infrastructure-as-code for consistent and repeatable deployments",
      "Developed a zero-trust security model with comprehensive monitoring and alerting",
    ],
    technologies: [
      "AWS",
      "Kubernetes",
      "Docker",
      "Terraform",
      "Jenkins",
      "ELK Stack",
      "Prometheus",
      "Vault",
    ],
    testimonial: {
      quote:
        "The cloud migration and DevOps transformation that CodeKet implemented has been game-changing for our business. We've dramatically improved our release velocity while enhancing security and reducing costs.",
      author: "Alex Thompson",
      title: "CTO, TechSolutions",
    },
    results: [
      "Increased release frequency from monthly to multiple times daily",
      "Reduced infrastructure costs by 35% while improving performance",
      "Achieved 99.99% platform uptime (up from 98.5%)",
      "Decreased production issues by 78% through automated testing",
      "Reduced security vulnerabilities by 92% with automated scanning",
      "Improved developer productivity by 40% with streamlined workflows",
    ],
  },
  {
    id: 7,
    title: "E-commerce Personalization Engine",
    industry: "retail",
    services: ["development", "analytics", "cloud"],
    clientName: "Fashion Forward Retailers",
    clientDescription:
      "A multi-brand fashion retailer with 12M+ online customers and $500M+ in annual online sales",
    challengeTitle: "Generic Customer Experience and Conversion Challenges",
    challengeDescription:
      "FFR was struggling with low conversion rates, high cart abandonment, and an inability to deliver personalized shopping experiences at scale. Their existing recommendation system was based on simple rules rather than customer behavior and preferences, resulting in generic suggestions and missed sales opportunities.",
    icon: <FaShoppingCart className="text-pink-500" />,
    bgColor: "from-pink-500/20 to-purple-500/20",
    accentColor: "pink",
    image: "/images/case-studies/ecommerce.jpg",
    logo: "/images/clients/ffr-logo.svg",
    stats: [
      { label: "Conversion Rate", value: "+32%" },
      { label: "Average Order Value", value: "+18%" },
      { label: "Revenue Increase", value: "$38M" },
      { label: "Cart Abandonment", value: "-25%" },
    ],
    solution: [
      "Developed a real-time personalization engine using machine learning and behavioral analytics",
      "Implemented dynamic product recommendations based on browsing history, purchase patterns, and similar customer profiles",
      "Created personalized email marketing automation with individualized product suggestions",
      "Built a customer segmentation system for targeted promotions and messaging",
    ],
    technologies: [
      "React",
      "Python",
      "TensorFlow",
      "AWS",
      "Elasticsearch",
      "Redis",
      "Kafka",
    ],
    testimonial: {
      quote:
        "The personalization engine that CodeKet built has completely transformed our online shopping experience. Our customers now receive truly relevant recommendations, and the impact on our conversion rates and revenue has been substantial.",
      author: "Emily Chen",
      title: "Digital Director, Fashion Forward Retailers",
    },
    results: [
      "Increased conversion rates by 32% through personalized product recommendations",
      "Improved average order value by 18% with relevant cross-selling",
      "Reduced cart abandonment rates by 25% using targeted incentives",
      "Generated $38M in additional annual revenue through personalization",
      "Increased email marketing effectiveness by 85% with personalized content",
      "Improved customer retention rate by 28% year-over-year",
    ],
  },
  {
    id: 8,
    title: "Enterprise Security Operations Center",
    industry: "finance",
    services: ["security", "analytics", "automation"],
    clientName: "Capital Finance Group",
    clientDescription:
      "A financial services leader managing over $200B in assets with strict regulatory compliance requirements",
    challengeTitle: "Evolving Cyber Threats and Compliance Mandates",
    challengeDescription:
      "CFG was facing increasingly sophisticated cyber threats while struggling to maintain compliance with expanding financial regulations. Their security team was overwhelmed by alert fatigue, and manual threat investigation processes were too slow to effectively respond to advanced attacks.",
    icon: <FaUserShield className="text-red-500" />,
    bgColor: "from-red-500/20 to-rose-500/20",
    accentColor: "red",
    image: "/images/case-studies/security.jpg",
    logo: "/images/clients/cfg-logo.svg",
    stats: [
      { label: "Threat Detection", value: "4x faster" },
      { label: "False Positives", value: "-85%" },
      { label: "Compliance Costs", value: "-32%" },
      { label: "Security Incidents", value: "Zero" },
    ],
    solution: [
      "Designed and implemented a comprehensive Security Operations Center (SOC) with 24/7 monitoring",
      "Developed AI-powered threat detection and correlation engine to identify complex attack patterns",
      "Created automated incident response playbooks for common security scenarios",
      "Built a compliance automation system for continuous regulatory adherence",
      "Implemented a security awareness training platform for employees",
    ],
    technologies: [
      "Elastic SIEM",
      "Python",
      "AWS Security Hub",
      "Terraform",
      "Splunk",
      "Palo Alto Networks",
      "MITRE ATT&CK",
    ],
    testimonial: {
      quote:
        "CodeKet's Security Operations Center has dramatically improved our security posture while reducing operational burden. Their AI-powered threat detection helps us identify advanced attacks before they impact our business.",
      author: "Victoria Reynolds",
      title: "CISO, Capital Finance Group",
    },
    results: [
      "Accelerated threat detection and response times by 4x",
      "Reduced false positive alerts by 85%, focusing team on real threats",
      "Decreased security compliance costs by 32% through automation",
      "Maintained zero successful security breaches since implementation",
      "Improved regulatory audit outcomes with comprehensive security documentation",
      "Enhanced overall security posture with proactive threat hunting capabilities",
    ],
  },
];
